#!/usr/bin/env bash
#SSH client configuration
Host *
        PasswordAuthentication no
        IdentityFile ~/.ssh/ubuntu
        SendEnv  LANG LS_*
        HashKnownHosts yes
        GSSAPIAuthentication yes
        GSSAPIDelegateCredentials no