#!/usr/bin/env bash
#SSH client configuration
Host *
        PasswordAuthentication no
        IdentityFile ~/.ssh/ubuntu
        SendEnv  LANG LS_*
        HashKnownHosts yes
        GSSAPIAuthentication yes
        GSSAPIDelegateCredentials no

ssh-copy-id ubuntu@52.3.242.0       
